package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemDo;
import com.miaoshaproject.dataobject.ItemDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    long countByExample(ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int deleteByExample(ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int insert(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int insertSelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    List<ItemDo> selectByExample(ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    ItemDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") ItemDo record, @Param("example") ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int updateByExample(@Param("record") ItemDo record, @Param("example") ItemDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int updateByPrimaryKey(ItemDo record);
}