package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemStockDo;
import com.miaoshaproject.dataobject.ItemStockDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemStockDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    long countByExample(ItemStockDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int deleteByExample(ItemStockDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int insert(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int insertSelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    List<ItemStockDo> selectByExample(ItemStockDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    ItemStockDo selectByPrimaryKey(Integer id);

    ItemStockDo selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") ItemStockDo record, @Param("example") ItemStockDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int updateByExample(@Param("record") ItemStockDo record, @Param("example") ItemStockDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Jun 16 16:32:13 CST 2019
     */
    int updateByPrimaryKey(ItemStockDo record);
}